server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://XXXX:3306/jm-ureport?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: XXXX
    password: XXXX
    driver-class-name: com.mysql.cj.jdbc.Driver



