server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://101.200.204.47:3306/jm-ureport?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: czhroot
    driver-class-name: com.mysql.cj.jdbc.Driver


platform:
  datasource:
    host: 101.200.204.47
    port: 3306
    dbname: jm-ureport
    username: root
    password: czhroot


